/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.plc4x.malbec.projecttype.configphoebus;



final class PhoebusPanel extends javax.swing.JPanel {

    private final PhoebusOptionsPanelController controller;

    PhoebusPanel(PhoebusOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
        txtRutaPhoebus.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                controller.changed();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                controller.changed();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                controller.changed();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRutaPhoebus = new javax.swing.JTextField();
        btnExaminar = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PhoebusPanel.class, "PhoebusPanel.jLabel1.text")); // NOI18N

        txtRutaPhoebus.setText(org.openide.util.NbBundle.getMessage(PhoebusPanel.class, "PhoebusPanel.txtRutaPhoebus.text")); // NOI18N
        txtRutaPhoebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaPhoebusActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnExaminar, org.openide.util.NbBundle.getMessage(PhoebusPanel.class, "PhoebusPanel.btnExaminar.text")); // NOI18N
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRutaPhoebus, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExaminar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutaPhoebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminar))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed

        boolean esWindows = System.getProperty("os.name").toLowerCase().contains("win");
        String extensionRequerida = esWindows ? "bat" : "sh";
        String descripcionFiltro = esWindows ? "Script de Windows (*.bat)" : "Script de Linux/Unix (*.sh)";

        org.openide.filesystems.FileChooserBuilder builder = new org.openide.filesystems.FileChooserBuilder("DirectorioPhoebus")
                .setTitle("Seleccionar ejecutable de CS-Studio Phoebus")
                .setFilesOnly(true);

        javax.swing.filechooser.FileNameExtensionFilter filtro
                = new javax.swing.filechooser.FileNameExtensionFilter(descripcionFiltro, extensionRequerida);
        builder.setFileFilter(filtro);

        java.io.File archivoSeleccionado = builder.showOpenDialog();

        if (archivoSeleccionado != null) {
            String ruta = archivoSeleccionado.getAbsolutePath();

            if (!ruta.toLowerCase().endsWith("." + extensionRequerida)) {
                org.openide.DialogDisplayer.getDefault().notify(
                        new org.openide.NotifyDescriptor.Message(
                                "Archivo inválido. En este sistema operativo debe seleccionar un archivo con extensión ." + extensionRequerida,
                                org.openide.NotifyDescriptor.WARNING_MESSAGE
                        )
                );
                return; 
            }

            txtRutaPhoebus.setText(ruta);
        }


    }//GEN-LAST:event_btnExaminarActionPerformed

    public String getRutaPhoebus() {
        return txtRutaPhoebus.getText();
    }

    public void setRutaPhoebus(String ruta) {
        txtRutaPhoebus.setText(ruta);
    }

    private void txtRutaPhoebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaPhoebusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaPhoebusActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(PhoebusPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(PhoebusPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(PhoebusPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(PhoebusPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExaminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRutaPhoebus;
    // End of variables declaration//GEN-END:variables
}
